"""empty message

Revision ID: 0268c485fe0b
Revises: a42ec385b747
Create Date: 2023-05-31 09:50:13.843110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0268c485fe0b'
down_revision = 'a42ec385b747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'headingvaluefound')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('headingvaluefound', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
