"""empty message

Revision ID: 383c0deac9b4
Revises: f09e7aa0d0c8
Create Date: 2023-05-29 12:04:25.294463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '383c0deac9b4'
down_revision = 'f09e7aa0d0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('reports', sa.Column('report_data_stored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'report_data_stored')
    op.drop_column('reports', 'report_data')
    # ### end Alembic commands ###
