"""empty message

Revision ID: a42ec385b747
Revises: 383c0deac9b4
Create Date: 2023-05-31 09:43:24.032201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42ec385b747'
down_revision = '383c0deac9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('headervalue', sa.String(length=300), nullable=True))
    op.add_column('reports', sa.Column('headingvaluefound', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'headingvaluefound')
    op.drop_column('reports', 'headervalue')
    # ### end Alembic commands ###
